// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartSyncTransport`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `move_atendimento_etapa`, `send_outbound_message`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalEngineApi>>
abstract class LocalEngineApi implements RustOpaqueInterface {
  /// Garante uma mídia no cache local (baixa uma vez, valida por hash).
  Future<String> ensureMedia({
    required String url,
    required String sha256Esperado,
  });

  /// Carrega o thread (histórico) de um atendimento (offline, índice).
  Future<List<MensagemThreadFfi>> getThread({
    required PlatformInt64 atendimentoId,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  /// Ingesta (upsert) um resumo de atendimento no índice — alimenta o cache
  /// local a partir de dados vindos do servidor.
  Future<void> ingestAtendimento({required AtendimentoResumoFfi a});

  /// Ingesta (upsert) uma mensagem no índice local.
  Future<void> ingestMensagem({required MensagemThreadFfi m});

  /// Lista a fila de atendimentos por status/departamento (offline, índice).
  Future<List<AtendimentoResumoFfi>> listAtendimentos({
    required String status,
    PlatformInt64? departamentoId,
    required PlatformInt64 limit,
  });

  /// Move o atendimento de etapa: aplica otimista no índice e enfileira o sync.
  Future<void> moveAtendimentoEtapa({
    required PlatformInt64 atendimentoId,
    required PlatformInt64 etapaDestinoId,
    required String motivo,
  });

  /// Abre o motor local: cria/migra o índice SQLite e prepara fila e cache.
  ///
  /// [db_path] é o arquivo do índice; [media_dir] o diretório do cache de mídia
  /// (ex.: sob `%APPDATA%` no Windows); [tenant_id] rotula eventos locais.
  static Future<LocalEngineApi> open({
    required String dbPath,
    required String mediaDir,
    required String tenantId,
  }) => RustLib.instance.api.crateApiAtendimentoLocalEngineApiOpen(
    dbPath: dbPath,
    mediaDir: mediaDir,
    tenantId: tenantId,
  );

  /// Envia mensagem outbound: grava pendente (id client-side) e enfileira o
  /// sync. Devolve o id local atribuído. `conteudo` é PII — nunca logar.
  Future<PlatformInt64> sendOutboundMessage({
    required PlatformInt64 atendimentoId,
    required String conteudo,
    required String tipo,
  });

  /// Sincroniza a fila offline com o servidor. A resolução last-write-wins e a
  /// marcação de sincronizadas ficam no `local_engine` (Rust); o **transporte**
  /// é injetado como dois callbacks Dart — [on_move] e [on_send] — que chamam o
  /// gRPC autenticado do lado Dart. Cada callback recebe o `action_id` (uuid,
  /// chave de idempotência) e devolve uma `String`: vazia = sucesso; não vazia =
  /// erro (a ação fica na fila para retry). `conteudo` é PII — nunca logar.
  Future<SyncReportFfi> sincronizar({
    required FutureOr<String> Function(
      String,
      PlatformInt64,
      PlatformInt64,
      String,
    )
    onMove,
    required FutureOr<String> Function(String, PlatformInt64, String, String)
    onSend,
  });

  /// Assina o stream local de eventos (mutações otimistas). Encaminha cada
  /// evento do bus `broadcast` do motor para o [sink] do Dart. Emite só os
  /// eventos locais; o merge com o realtime do servidor é da camada acima.
  Stream<AtendimentoEventoFfi> streamAtendimentos();
}

/// Evento realtime local na fronteira FFI. `payload` vai como JSON (string).
class AtendimentoEventoFfi {
  final String tipo;
  final String tenantId;
  final String payloadJson;

  const AtendimentoEventoFfi({
    required this.tipo,
    required this.tenantId,
    required this.payloadJson,
  });

  @override
  int get hashCode => tipo.hashCode ^ tenantId.hashCode ^ payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AtendimentoEventoFfi &&
          runtimeType == other.runtimeType &&
          tipo == other.tipo &&
          tenantId == other.tenantId &&
          payloadJson == other.payloadJson;
}

/// Resumo de atendimento na fronteira FFI (datas em epoch-millis).
class AtendimentoResumoFfi {
  final PlatformInt64 id;
  final PlatformInt64 contatoId;
  final String status;
  final PlatformInt64? departamentoId;
  final PlatformInt64? fluxoAtendimentoId;
  final PlatformInt64? etapaAtualId;
  final String assunto;
  final String prioridade;
  final PlatformInt64? atendenteHumanoId;
  final PlatformInt64 dataInicio;
  final PlatformInt64? dataUltimaMensagem;

  const AtendimentoResumoFfi({
    required this.id,
    required this.contatoId,
    required this.status,
    this.departamentoId,
    this.fluxoAtendimentoId,
    this.etapaAtualId,
    required this.assunto,
    required this.prioridade,
    this.atendenteHumanoId,
    required this.dataInicio,
    this.dataUltimaMensagem,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      contatoId.hashCode ^
      status.hashCode ^
      departamentoId.hashCode ^
      fluxoAtendimentoId.hashCode ^
      etapaAtualId.hashCode ^
      assunto.hashCode ^
      prioridade.hashCode ^
      atendenteHumanoId.hashCode ^
      dataInicio.hashCode ^
      dataUltimaMensagem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AtendimentoResumoFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contatoId == other.contatoId &&
          status == other.status &&
          departamentoId == other.departamentoId &&
          fluxoAtendimentoId == other.fluxoAtendimentoId &&
          etapaAtualId == other.etapaAtualId &&
          assunto == other.assunto &&
          prioridade == other.prioridade &&
          atendenteHumanoId == other.atendenteHumanoId &&
          dataInicio == other.dataInicio &&
          dataUltimaMensagem == other.dataUltimaMensagem;
}

/// Mensagem de thread na fronteira FFI. `conteudo` é PII — nunca logar.
class MensagemThreadFfi {
  final PlatformInt64 id;
  final PlatformInt64 atendimentoId;
  final String tipo;
  final String conteudo;
  final String remetente;
  final PlatformInt64 timestamp;
  final String statusEnvio;
  final bool geradoPorIa;
  final String? resumoMidia;

  const MensagemThreadFfi({
    required this.id,
    required this.atendimentoId,
    required this.tipo,
    required this.conteudo,
    required this.remetente,
    required this.timestamp,
    required this.statusEnvio,
    required this.geradoPorIa,
    this.resumoMidia,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      atendimentoId.hashCode ^
      tipo.hashCode ^
      conteudo.hashCode ^
      remetente.hashCode ^
      timestamp.hashCode ^
      statusEnvio.hashCode ^
      geradoPorIa.hashCode ^
      resumoMidia.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MensagemThreadFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          atendimentoId == other.atendimentoId &&
          tipo == other.tipo &&
          conteudo == other.conteudo &&
          remetente == other.remetente &&
          timestamp == other.timestamp &&
          statusEnvio == other.statusEnvio &&
          geradoPorIa == other.geradoPorIa &&
          resumoMidia == other.resumoMidia;
}

/// Relatório de uma passada de sincronização na fronteira FFI.
class SyncReportFfi {
  /// Ações aplicadas com sucesso no servidor.
  final PlatformInt64 aplicadas;

  /// Ações superadas pela resolução last-write-wins (não enviadas).
  final PlatformInt64 descartadasLww;

  /// Ações que falharam no transporte (permanecem na fila para retry).
  final PlatformInt64 falhas;

  const SyncReportFfi({
    required this.aplicadas,
    required this.descartadasLww,
    required this.falhas,
  });

  @override
  int get hashCode =>
      aplicadas.hashCode ^ descartadasLww.hashCode ^ falhas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReportFfi &&
          runtimeType == other.runtimeType &&
          aplicadas == other.aplicadas &&
          descartadasLww == other.descartadasLww &&
          falhas == other.falhas;
}
