// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class UpdateInfo {
  /// The available version that we are updating to.
  final VelopackAsset targetFullRelease;

  /// The base release that this update is based on. This is only available if the update is a delta update.
  final VelopackAsset? baseRelease;

  /// The list of delta updates that can be applied to the base version to get to the target version.
  final List<VelopackAsset> deltasToTarget;

  /// True if the update is a version downgrade or lateral move (such as when switching channels to the same version number).
  /// In this case, only full updates are allowed, and any local packages on disk newer than the downloaded version will be
  /// deleted.
  final bool isDowngrade;

  const UpdateInfo({
    required this.targetFullRelease,
    this.baseRelease,
    required this.deltasToTarget,
    required this.isDowngrade,
  });

  @override
  int get hashCode =>
      targetFullRelease.hashCode ^
      baseRelease.hashCode ^
      deltasToTarget.hashCode ^
      isDowngrade.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateInfo &&
          runtimeType == other.runtimeType &&
          targetFullRelease == other.targetFullRelease &&
          baseRelease == other.baseRelease &&
          deltasToTarget == other.deltasToTarget &&
          isDowngrade == other.isDowngrade;
}

class VelopackAsset {
  /// The name or Id of the package containing this release.
  final String packageId;

  /// The version of this release.
  final String version;

  /// The type of asset (eg. "Full" or "Delta").
  final String type;

  /// The filename of the update package containing this release.
  final String fileName;

  /// The SHA1 checksum of the update package containing this release.
  final String sha1;

  /// The SHA256 checksum of the update package containing this release.
  final String sha256;

  /// The size in bytes of the update package containing this release.
  final BigInt size;

  /// The release notes in markdown format, as passed to Velopack when packaging the release. This may be an empty string.
  final String notesMarkdown;

  /// The release notes in HTML format, transformed from Markdown when packaging the release. This may be an empty string.
  final String notesHtml;

  const VelopackAsset({
    required this.packageId,
    required this.version,
    required this.type,
    required this.fileName,
    required this.sha1,
    required this.sha256,
    required this.size,
    required this.notesMarkdown,
    required this.notesHtml,
  });

  @override
  int get hashCode =>
      packageId.hashCode ^
      version.hashCode ^
      type.hashCode ^
      fileName.hashCode ^
      sha1.hashCode ^
      sha256.hashCode ^
      size.hashCode ^
      notesMarkdown.hashCode ^
      notesHtml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VelopackAsset &&
          runtimeType == other.runtimeType &&
          packageId == other.packageId &&
          version == other.version &&
          type == other.type &&
          fileName == other.fileName &&
          sha1 == other.sha1 &&
          sha256 == other.sha256 &&
          size == other.size &&
          notesMarkdown == other.notesMarkdown &&
          notesHtml == other.notesHtml;
}
