// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/atendimento.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 283841559;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'local_engine_ffi',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAtendimentoLocalEngineApiEnsureMedia({
    required LocalEngineApi that,
    required String url,
    required String sha256Esperado,
  });

  Future<List<MensagemThreadFfi>> crateApiAtendimentoLocalEngineApiGetThread({
    required LocalEngineApi that,
    required PlatformInt64 atendimentoId,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  Future<void> crateApiAtendimentoLocalEngineApiIngestAtendimento({
    required LocalEngineApi that,
    required AtendimentoResumoFfi a,
  });

  Future<void> crateApiAtendimentoLocalEngineApiIngestMensagem({
    required LocalEngineApi that,
    required MensagemThreadFfi m,
  });

  Future<List<AtendimentoResumoFfi>>
  crateApiAtendimentoLocalEngineApiListAtendimentos({
    required LocalEngineApi that,
    required String status,
    PlatformInt64? departamentoId,
    required PlatformInt64 limit,
  });

  Future<void> crateApiAtendimentoLocalEngineApiMoveAtendimentoEtapa({
    required LocalEngineApi that,
    required PlatformInt64 atendimentoId,
    required PlatformInt64 etapaDestinoId,
    required String motivo,
  });

  Future<LocalEngineApi> crateApiAtendimentoLocalEngineApiOpen({
    required String dbPath,
    required String mediaDir,
    required String tenantId,
  });

  Future<PlatformInt64> crateApiAtendimentoLocalEngineApiSendOutboundMessage({
    required LocalEngineApi that,
    required PlatformInt64 atendimentoId,
    required String conteudo,
    required String tipo,
  });

  Future<SyncReportFfi> crateApiAtendimentoLocalEngineApiSincronizar({
    required LocalEngineApi that,
    required FutureOr<String> Function(
      String,
      PlatformInt64,
      PlatformInt64,
      String,
    )
    onMove,
    required FutureOr<String> Function(String, PlatformInt64, String, String)
    onSend,
  });

  Stream<AtendimentoEventoFfi>
  crateApiAtendimentoLocalEngineApiStreamAtendimentos({
    required LocalEngineApi that,
  });

  Future<void> crateApiInitInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocalEngineApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocalEngineApi;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocalEngineApiPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAtendimentoLocalEngineApiEnsureMedia({
    required LocalEngineApi that,
    required String url,
    required String sha256Esperado,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          sse_encode_String(sha256Esperado, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAtendimentoLocalEngineApiEnsureMediaConstMeta,
        argValues: [that, url, sha256Esperado],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtendimentoLocalEngineApiEnsureMediaConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_ensure_media",
        argNames: ["that", "url", "sha256Esperado"],
      );

  @override
  Future<List<MensagemThreadFfi>> crateApiAtendimentoLocalEngineApiGetThread({
    required LocalEngineApi that,
    required PlatformInt64 atendimentoId,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_i_64(atendimentoId, serializer);
          sse_encode_i_64(limit, serializer);
          sse_encode_i_64(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mensagem_thread_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAtendimentoLocalEngineApiGetThreadConstMeta,
        argValues: [that, atendimentoId, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtendimentoLocalEngineApiGetThreadConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_get_thread",
        argNames: ["that", "atendimentoId", "limit", "offset"],
      );

  @override
  Future<void> crateApiAtendimentoLocalEngineApiIngestAtendimento({
    required LocalEngineApi that,
    required AtendimentoResumoFfi a,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_box_autoadd_atendimento_resumo_ffi(a, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAtendimentoLocalEngineApiIngestAtendimentoConstMeta,
        argValues: [that, a],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAtendimentoLocalEngineApiIngestAtendimentoConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_ingest_atendimento",
        argNames: ["that", "a"],
      );

  @override
  Future<void> crateApiAtendimentoLocalEngineApiIngestMensagem({
    required LocalEngineApi that,
    required MensagemThreadFfi m,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_box_autoadd_mensagem_thread_ffi(m, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAtendimentoLocalEngineApiIngestMensagemConstMeta,
        argValues: [that, m],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtendimentoLocalEngineApiIngestMensagemConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_ingest_mensagem",
        argNames: ["that", "m"],
      );

  @override
  Future<List<AtendimentoResumoFfi>>
  crateApiAtendimentoLocalEngineApiListAtendimentos({
    required LocalEngineApi that,
    required String status,
    PlatformInt64? departamentoId,
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_String(status, serializer);
          sse_encode_opt_box_autoadd_i_64(departamentoId, serializer);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_atendimento_resumo_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAtendimentoLocalEngineApiListAtendimentosConstMeta,
        argValues: [that, status, departamentoId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAtendimentoLocalEngineApiListAtendimentosConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_list_atendimentos",
        argNames: ["that", "status", "departamentoId", "limit"],
      );

  @override
  Future<void> crateApiAtendimentoLocalEngineApiMoveAtendimentoEtapa({
    required LocalEngineApi that,
    required PlatformInt64 atendimentoId,
    required PlatformInt64 etapaDestinoId,
    required String motivo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_i_64(atendimentoId, serializer);
          sse_encode_i_64(etapaDestinoId, serializer);
          sse_encode_String(motivo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAtendimentoLocalEngineApiMoveAtendimentoEtapaConstMeta,
        argValues: [that, atendimentoId, etapaDestinoId, motivo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAtendimentoLocalEngineApiMoveAtendimentoEtapaConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_move_atendimento_etapa",
        argNames: ["that", "atendimentoId", "etapaDestinoId", "motivo"],
      );

  @override
  Future<LocalEngineApi> crateApiAtendimentoLocalEngineApiOpen({
    required String dbPath,
    required String mediaDir,
    required String tenantId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(mediaDir, serializer);
          sse_encode_String(tenantId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAtendimentoLocalEngineApiOpenConstMeta,
        argValues: [dbPath, mediaDir, tenantId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtendimentoLocalEngineApiOpenConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_open",
        argNames: ["dbPath", "mediaDir", "tenantId"],
      );

  @override
  Future<PlatformInt64> crateApiAtendimentoLocalEngineApiSendOutboundMessage({
    required LocalEngineApi that,
    required PlatformInt64 atendimentoId,
    required String conteudo,
    required String tipo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_i_64(atendimentoId, serializer);
          sse_encode_String(conteudo, serializer);
          sse_encode_String(tipo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAtendimentoLocalEngineApiSendOutboundMessageConstMeta,
        argValues: [that, atendimentoId, conteudo, tipo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAtendimentoLocalEngineApiSendOutboundMessageConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_send_outbound_message",
        argNames: ["that", "atendimentoId", "conteudo", "tipo"],
      );

  @override
  Future<SyncReportFfi> crateApiAtendimentoLocalEngineApiSincronizar({
    required LocalEngineApi that,
    required FutureOr<String> Function(
      String,
      PlatformInt64,
      PlatformInt64,
      String,
    )
    onMove,
    required FutureOr<String> Function(String, PlatformInt64, String, String)
    onSend,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
            that,
            serializer,
          );
          sse_encode_DartFn_Inputs_String_i_64_i_64_String_Output_String_AnyhowException(
            onMove,
            serializer,
          );
          sse_encode_DartFn_Inputs_String_i_64_String_String_Output_String_AnyhowException(
            onSend,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_report_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAtendimentoLocalEngineApiSincronizarConstMeta,
        argValues: [that, onMove, onSend],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtendimentoLocalEngineApiSincronizarConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_sincronizar",
        argNames: ["that", "onMove", "onSend"],
      );

  @override
  Stream<AtendimentoEventoFfi>
  crateApiAtendimentoLocalEngineApiStreamAtendimentos({
    required LocalEngineApi that,
  }) {
    final sink = RustStreamSink<AtendimentoEventoFfi>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
              that,
              serializer,
            );
            sse_encode_StreamSink_atendimento_evento_ffi_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiAtendimentoLocalEngineApiStreamAtendimentosConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiAtendimentoLocalEngineApiStreamAtendimentosConstMeta =>
      const TaskConstMeta(
        debugName: "LocalEngineApi_stream_atendimentos",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  Future<void> Function(int, dynamic, dynamic, dynamic, dynamic)
  encode_DartFn_Inputs_String_i_64_String_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, PlatformInt64, String, String) raw,
  ) {
    return (callId, rawArg0, rawArg1, rawArg2, rawArg3) async {
      final arg0 = dco_decode_String(rawArg0);
      final arg1 = dco_decode_i_64(rawArg1);
      final arg2 = dco_decode_String(rawArg2);
      final arg3 = dco_decode_String(rawArg3);

      Box<String>? rawOutput;
      Box<AnyhowException>? rawError;
      try {
        rawOutput = Box(await raw(arg0, arg1, arg2, arg3));
      } catch (e, s) {
        rawError = Box(AnyhowException("$e\n\n$s"));
      }

      final serializer = SseSerializer(generalizedFrbRustBinding);
      assert((rawOutput != null) ^ (rawError != null));
      if (rawOutput != null) {
        serializer.buffer.putUint8(0);
        sse_encode_String(rawOutput.value, serializer);
      } else {
        serializer.buffer.putUint8(1);
        sse_encode_AnyhowException(rawError!.value, serializer);
      }
      final output = serializer.intoRaw();

      generalizedFrbRustBinding.dartFnDeliverOutput(
        callId: callId,
        ptr: output.ptr,
        rustVecLen: output.rustVecLen,
        dataLen: output.dataLen,
      );
    };
  }

  Future<void> Function(int, dynamic, dynamic, dynamic, dynamic)
  encode_DartFn_Inputs_String_i_64_i_64_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, PlatformInt64, PlatformInt64, String) raw,
  ) {
    return (callId, rawArg0, rawArg1, rawArg2, rawArg3) async {
      final arg0 = dco_decode_String(rawArg0);
      final arg1 = dco_decode_i_64(rawArg1);
      final arg2 = dco_decode_i_64(rawArg2);
      final arg3 = dco_decode_String(rawArg3);

      Box<String>? rawOutput;
      Box<AnyhowException>? rawError;
      try {
        rawOutput = Box(await raw(arg0, arg1, arg2, arg3));
      } catch (e, s) {
        rawError = Box(AnyhowException("$e\n\n$s"));
      }

      final serializer = SseSerializer(generalizedFrbRustBinding);
      assert((rawOutput != null) ^ (rawError != null));
      if (rawOutput != null) {
        serializer.buffer.putUint8(0);
        sse_encode_String(rawOutput.value, serializer);
      } else {
        serializer.buffer.putUint8(1);
        sse_encode_AnyhowException(rawError!.value, serializer);
      }
      final output = serializer.intoRaw();

      generalizedFrbRustBinding.dartFnDeliverOutput(
        callId: callId,
        ptr: output.ptr,
        rustVecLen: output.rustVecLen,
        dataLen: output.dataLen,
      );
    };
  }

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocalEngineApi => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocalEngineApi => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  LocalEngineApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocalEngineApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocalEngineApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocalEngineApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FutureOr<String> Function(String, PlatformInt64, String, String)
  dco_decode_DartFn_Inputs_String_i_64_String_String_Output_String_AnyhowException(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError('');
  }

  @protected
  FutureOr<String> Function(String, PlatformInt64, PlatformInt64, String)
  dco_decode_DartFn_Inputs_String_i_64_i_64_String_Output_String_AnyhowException(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError('');
  }

  @protected
  Object dco_decode_DartOpaque(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return decodeDartOpaque(raw, generalizedFrbRustBinding);
  }

  @protected
  LocalEngineApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocalEngineApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<AtendimentoEventoFfi>
  dco_decode_StreamSink_atendimento_evento_ffi_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AtendimentoEventoFfi dco_decode_atendimento_evento_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AtendimentoEventoFfi(
      tipo: dco_decode_String(arr[0]),
      tenantId: dco_decode_String(arr[1]),
      payloadJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  AtendimentoResumoFfi dco_decode_atendimento_resumo_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return AtendimentoResumoFfi(
      id: dco_decode_i_64(arr[0]),
      contatoId: dco_decode_i_64(arr[1]),
      status: dco_decode_String(arr[2]),
      departamentoId: dco_decode_opt_box_autoadd_i_64(arr[3]),
      fluxoAtendimentoId: dco_decode_opt_box_autoadd_i_64(arr[4]),
      etapaAtualId: dco_decode_opt_box_autoadd_i_64(arr[5]),
      assunto: dco_decode_String(arr[6]),
      prioridade: dco_decode_String(arr[7]),
      atendenteHumanoId: dco_decode_opt_box_autoadd_i_64(arr[8]),
      dataInicio: dco_decode_i_64(arr[9]),
      dataUltimaMensagem: dco_decode_opt_box_autoadd_i_64(arr[10]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AtendimentoResumoFfi dco_decode_box_autoadd_atendimento_resumo_ffi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_atendimento_resumo_ffi(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MensagemThreadFfi dco_decode_box_autoadd_mensagem_thread_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mensagem_thread_ffi(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<AtendimentoResumoFfi> dco_decode_list_atendimento_resumo_ffi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_atendimento_resumo_ffi)
        .toList();
  }

  @protected
  List<MensagemThreadFfi> dco_decode_list_mensagem_thread_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mensagem_thread_ffi).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MensagemThreadFfi dco_decode_mensagem_thread_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MensagemThreadFfi(
      id: dco_decode_i_64(arr[0]),
      atendimentoId: dco_decode_i_64(arr[1]),
      tipo: dco_decode_String(arr[2]),
      conteudo: dco_decode_String(arr[3]),
      remetente: dco_decode_String(arr[4]),
      timestamp: dco_decode_i_64(arr[5]),
      statusEnvio: dco_decode_String(arr[6]),
      geradoPorIa: dco_decode_bool(arr[7]),
      resumoMidia: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  SyncReportFfi dco_decode_sync_report_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SyncReportFfi(
      aplicadas: dco_decode_i_64(arr[0]),
      descartadasLww: dco_decode_i_64(arr[1]),
      falhas: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  LocalEngineApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocalEngineApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocalEngineApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocalEngineApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_isize(deserializer);
    return decodeDartOpaque(inner, generalizedFrbRustBinding);
  }

  @protected
  LocalEngineApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocalEngineApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<AtendimentoEventoFfi>
  sse_decode_StreamSink_atendimento_evento_ffi_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AtendimentoEventoFfi sse_decode_atendimento_evento_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tipo = sse_decode_String(deserializer);
    var var_tenantId = sse_decode_String(deserializer);
    var var_payloadJson = sse_decode_String(deserializer);
    return AtendimentoEventoFfi(
      tipo: var_tipo,
      tenantId: var_tenantId,
      payloadJson: var_payloadJson,
    );
  }

  @protected
  AtendimentoResumoFfi sse_decode_atendimento_resumo_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_contatoId = sse_decode_i_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_departamentoId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_fluxoAtendimentoId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_etapaAtualId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_assunto = sse_decode_String(deserializer);
    var var_prioridade = sse_decode_String(deserializer);
    var var_atendenteHumanoId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_dataInicio = sse_decode_i_64(deserializer);
    var var_dataUltimaMensagem = sse_decode_opt_box_autoadd_i_64(deserializer);
    return AtendimentoResumoFfi(
      id: var_id,
      contatoId: var_contatoId,
      status: var_status,
      departamentoId: var_departamentoId,
      fluxoAtendimentoId: var_fluxoAtendimentoId,
      etapaAtualId: var_etapaAtualId,
      assunto: var_assunto,
      prioridade: var_prioridade,
      atendenteHumanoId: var_atendenteHumanoId,
      dataInicio: var_dataInicio,
      dataUltimaMensagem: var_dataUltimaMensagem,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AtendimentoResumoFfi sse_decode_box_autoadd_atendimento_resumo_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_atendimento_resumo_ffi(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MensagemThreadFfi sse_decode_box_autoadd_mensagem_thread_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mensagem_thread_ffi(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<AtendimentoResumoFfi> sse_decode_list_atendimento_resumo_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AtendimentoResumoFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_atendimento_resumo_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  List<MensagemThreadFfi> sse_decode_list_mensagem_thread_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MensagemThreadFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mensagem_thread_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MensagemThreadFfi sse_decode_mensagem_thread_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_atendimentoId = sse_decode_i_64(deserializer);
    var var_tipo = sse_decode_String(deserializer);
    var var_conteudo = sse_decode_String(deserializer);
    var var_remetente = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_statusEnvio = sse_decode_String(deserializer);
    var var_geradoPorIa = sse_decode_bool(deserializer);
    var var_resumoMidia = sse_decode_opt_String(deserializer);
    return MensagemThreadFfi(
      id: var_id,
      atendimentoId: var_atendimentoId,
      tipo: var_tipo,
      conteudo: var_conteudo,
      remetente: var_remetente,
      timestamp: var_timestamp,
      statusEnvio: var_statusEnvio,
      geradoPorIa: var_geradoPorIa,
      resumoMidia: var_resumoMidia,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SyncReportFfi sse_decode_sync_report_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aplicadas = sse_decode_i_64(deserializer);
    var var_descartadasLww = sse_decode_i_64(deserializer);
    var var_falhas = sse_decode_i_64(deserializer);
    return SyncReportFfi(
      aplicadas: var_aplicadas,
      descartadasLww: var_descartadasLww,
      falhas: var_falhas,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    LocalEngineApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocalEngineApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    LocalEngineApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocalEngineApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_DartFn_Inputs_String_i_64_String_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, PlatformInt64, String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_DartOpaque(
      encode_DartFn_Inputs_String_i_64_String_String_Output_String_AnyhowException(
        self,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_DartFn_Inputs_String_i_64_i_64_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, PlatformInt64, PlatformInt64, String)
    self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_DartOpaque(
      encode_DartFn_Inputs_String_i_64_i_64_String_Output_String_AnyhowException(
        self,
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_isize(
      PlatformPointerUtil.ptrToPlatformInt64(
        encodeDartOpaque(
          self,
          portManager.dartHandlerPort,
          generalizedFrbRustBinding,
        ),
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    LocalEngineApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocalEngineApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_atendimento_evento_ffi_Sse(
    RustStreamSink<AtendimentoEventoFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_atendimento_evento_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_atendimento_evento_ffi(
    AtendimentoEventoFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tipo, serializer);
    sse_encode_String(self.tenantId, serializer);
    sse_encode_String(self.payloadJson, serializer);
  }

  @protected
  void sse_encode_atendimento_resumo_ffi(
    AtendimentoResumoFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.contatoId, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_box_autoadd_i_64(self.departamentoId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.fluxoAtendimentoId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.etapaAtualId, serializer);
    sse_encode_String(self.assunto, serializer);
    sse_encode_String(self.prioridade, serializer);
    sse_encode_opt_box_autoadd_i_64(self.atendenteHumanoId, serializer);
    sse_encode_i_64(self.dataInicio, serializer);
    sse_encode_opt_box_autoadd_i_64(self.dataUltimaMensagem, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_atendimento_resumo_ffi(
    AtendimentoResumoFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_atendimento_resumo_ffi(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mensagem_thread_ffi(
    MensagemThreadFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mensagem_thread_ffi(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_atendimento_resumo_ffi(
    List<AtendimentoResumoFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_atendimento_resumo_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mensagem_thread_ffi(
    List<MensagemThreadFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mensagem_thread_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mensagem_thread_ffi(
    MensagemThreadFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.atendimentoId, serializer);
    sse_encode_String(self.tipo, serializer);
    sse_encode_String(self.conteudo, serializer);
    sse_encode_String(self.remetente, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.statusEnvio, serializer);
    sse_encode_bool(self.geradoPorIa, serializer);
    sse_encode_opt_String(self.resumoMidia, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_sync_report_ffi(
    SyncReportFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.aplicadas, serializer);
    sse_encode_i_64(self.descartadasLww, serializer);
    sse_encode_i_64(self.falhas, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class LocalEngineApiImpl extends RustOpaque implements LocalEngineApi {
  // Not to be used by end users
  LocalEngineApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LocalEngineApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LocalEngineApi,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocalEngineApi,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocalEngineApiPtr,
  );

  /// Garante uma mídia no cache local (baixa uma vez, valida por hash).
  Future<String> ensureMedia({
    required String url,
    required String sha256Esperado,
  }) => RustLib.instance.api.crateApiAtendimentoLocalEngineApiEnsureMedia(
    that: this,
    url: url,
    sha256Esperado: sha256Esperado,
  );

  /// Carrega o thread (histórico) de um atendimento (offline, índice).
  Future<List<MensagemThreadFfi>> getThread({
    required PlatformInt64 atendimentoId,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) => RustLib.instance.api.crateApiAtendimentoLocalEngineApiGetThread(
    that: this,
    atendimentoId: atendimentoId,
    limit: limit,
    offset: offset,
  );

  /// Ingesta (upsert) um resumo de atendimento no índice — alimenta o cache
  /// local a partir de dados vindos do servidor.
  Future<void> ingestAtendimento({required AtendimentoResumoFfi a}) => RustLib
      .instance
      .api
      .crateApiAtendimentoLocalEngineApiIngestAtendimento(that: this, a: a);

  /// Ingesta (upsert) uma mensagem no índice local.
  Future<void> ingestMensagem({required MensagemThreadFfi m}) => RustLib
      .instance
      .api
      .crateApiAtendimentoLocalEngineApiIngestMensagem(that: this, m: m);

  /// Lista a fila de atendimentos por status/departamento (offline, índice).
  Future<List<AtendimentoResumoFfi>> listAtendimentos({
    required String status,
    PlatformInt64? departamentoId,
    required PlatformInt64 limit,
  }) => RustLib.instance.api.crateApiAtendimentoLocalEngineApiListAtendimentos(
    that: this,
    status: status,
    departamentoId: departamentoId,
    limit: limit,
  );

  /// Move o atendimento de etapa: aplica otimista no índice e enfileira o sync.
  Future<void> moveAtendimentoEtapa({
    required PlatformInt64 atendimentoId,
    required PlatformInt64 etapaDestinoId,
    required String motivo,
  }) => RustLib.instance.api
      .crateApiAtendimentoLocalEngineApiMoveAtendimentoEtapa(
        that: this,
        atendimentoId: atendimentoId,
        etapaDestinoId: etapaDestinoId,
        motivo: motivo,
      );

  /// Envia mensagem outbound: grava pendente (id client-side) e enfileira o
  /// sync. Devolve o id local atribuído. `conteudo` é PII — nunca logar.
  Future<PlatformInt64> sendOutboundMessage({
    required PlatformInt64 atendimentoId,
    required String conteudo,
    required String tipo,
  }) =>
      RustLib.instance.api.crateApiAtendimentoLocalEngineApiSendOutboundMessage(
        that: this,
        atendimentoId: atendimentoId,
        conteudo: conteudo,
        tipo: tipo,
      );

  /// Sincroniza a fila offline com o servidor. A resolução last-write-wins e a
  /// marcação de sincronizadas ficam no `local_engine` (Rust); o **transporte**
  /// é injetado como dois callbacks Dart — [on_move] e [on_send] — que chamam o
  /// gRPC autenticado do lado Dart. Cada callback recebe o `action_id` (uuid,
  /// chave de idempotência) e devolve uma `String`: vazia = sucesso; não vazia =
  /// erro (a ação fica na fila para retry). `conteudo` é PII — nunca logar.
  Future<SyncReportFfi> sincronizar({
    required FutureOr<String> Function(
      String,
      PlatformInt64,
      PlatformInt64,
      String,
    )
    onMove,
    required FutureOr<String> Function(String, PlatformInt64, String, String)
    onSend,
  }) => RustLib.instance.api.crateApiAtendimentoLocalEngineApiSincronizar(
    that: this,
    onMove: onMove,
    onSend: onSend,
  );

  /// Assina o stream local de eventos (mutações otimistas). Encaminha cada
  /// evento do bus `broadcast` do motor para o [sink] do Dart. Emite só os
  /// eventos locais; o merge com o realtime do servidor é da camada acima.
  Stream<AtendimentoEventoFfi> streamAtendimentos() => RustLib.instance.api
      .crateApiAtendimentoLocalEngineApiStreamAtendimentos(that: this);
}
