// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/atendimento.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocalEngineApiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  LocalEngineApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    dynamic raw,
  );

  @protected
  LocalEngineApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    dynamic raw,
  );

  @protected
  FutureOr<String> Function(String, PlatformInt64, String, String)
  dco_decode_DartFn_Inputs_String_i_64_String_String_Output_String_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<String> Function(String, PlatformInt64, PlatformInt64, String)
  dco_decode_DartFn_Inputs_String_i_64_i_64_String_Output_String_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  LocalEngineApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    dynamic raw,
  );

  @protected
  RustStreamSink<AtendimentoEventoFfi>
  dco_decode_StreamSink_atendimento_evento_ffi_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AtendimentoEventoFfi dco_decode_atendimento_evento_ffi(dynamic raw);

  @protected
  AtendimentoResumoFfi dco_decode_atendimento_resumo_ffi(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AtendimentoResumoFfi dco_decode_box_autoadd_atendimento_resumo_ffi(
    dynamic raw,
  );

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MensagemThreadFfi dco_decode_box_autoadd_mensagem_thread_ffi(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<AtendimentoResumoFfi> dco_decode_list_atendimento_resumo_ffi(
    dynamic raw,
  );

  @protected
  List<MensagemThreadFfi> dco_decode_list_mensagem_thread_ffi(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MensagemThreadFfi dco_decode_mensagem_thread_ffi(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SyncReportFfi dco_decode_sync_report_ffi(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  LocalEngineApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    SseDeserializer deserializer,
  );

  @protected
  LocalEngineApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  LocalEngineApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AtendimentoEventoFfi>
  sse_decode_StreamSink_atendimento_evento_ffi_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AtendimentoEventoFfi sse_decode_atendimento_evento_ffi(
    SseDeserializer deserializer,
  );

  @protected
  AtendimentoResumoFfi sse_decode_atendimento_resumo_ffi(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AtendimentoResumoFfi sse_decode_box_autoadd_atendimento_resumo_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MensagemThreadFfi sse_decode_box_autoadd_mensagem_thread_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<AtendimentoResumoFfi> sse_decode_list_atendimento_resumo_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<MensagemThreadFfi> sse_decode_list_mensagem_thread_ffi(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MensagemThreadFfi sse_decode_mensagem_thread_ffi(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SyncReportFfi sse_decode_sync_report_ffi(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    LocalEngineApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    LocalEngineApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_i_64_String_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, PlatformInt64, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_i_64_i_64_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, PlatformInt64, PlatformInt64, String)
    self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    LocalEngineApi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_atendimento_evento_ffi_Sse(
    RustStreamSink<AtendimentoEventoFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_atendimento_evento_ffi(
    AtendimentoEventoFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_atendimento_resumo_ffi(
    AtendimentoResumoFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_atendimento_resumo_ffi(
    AtendimentoResumoFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mensagem_thread_ffi(
    MensagemThreadFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_atendimento_resumo_ffi(
    List<AtendimentoResumoFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mensagem_thread_ffi(
    List<MensagemThreadFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mensagem_thread_ffi(
    MensagemThreadFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_report_ffi(SyncReportFfi self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalEngineApi(
    int ptr,
  );
}
