[package]
name = "contracts"
version = "0.1.0"
edition.workspace = true

[dependencies]
flatbuffers.workspace = true
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
flatc-rust.workspace = true
